"""Generate Text-to-SQL grounding artifacts from the current parquet warehouse."""
import json
from pathlib import Path
import pandas as pd
D=Path(__file__).resolve().parent.parent/'data'; OUT=Path(__file__).resolve().parent.parent/'artifacts'; OUT.mkdir(exist_ok=True)
TABLES=['customer_master','product_master','seller_master','agent_master','transactions','clickstream','inventory','returns','product_reviews','support_contacts','marketing_spend','mmm_weekly_target']
GRAIN={'product_master':'1 row per SKU','customer_master':'1 row per customer','seller_master':'1 row per seller','agent_master':'1 row per support agent','transactions':'1 row per order line / transaction_id; order_id groups lines','clickstream':'1 row per event; session_id groups events','inventory':'1 row per product x seller x warehouse x day','returns':'1 row per return','product_reviews':'1 row per product review','support_contacts':'1 row per support interaction','marketing_spend':'1 row per date x channel x region','mmm_weekly_target':'1 row per week'}
PK={'product_master':'product_id','customer_master':'customer_id','seller_master':'seller_id','agent_master':'agent_id','transactions':'transaction_id','clickstream':'event_id','returns':'return_id','product_reviews':'review_id','support_contacts':'contact_id','mmm_weekly_target':'week_start'}
FK={'product_master':['seller_id -> seller_master.seller_id'],'transactions':['customer_id -> customer_master.customer_id','product_id -> product_master.product_id','seller_id -> seller_master.seller_id'],'clickstream':['customer_id -> customer_master.customer_id','product_id -> product_master.product_id (nullable)'],'inventory':['product_id -> product_master.product_id','seller_id -> seller_master.seller_id'],'returns':['transaction_id -> transactions.transaction_id','customer_id -> customer_master.customer_id','product_id -> product_master.product_id'],'product_reviews':['customer_id -> customer_master.customer_id','product_id -> product_master.product_id','order_id -> transactions.order_id'],'support_contacts':['customer_id -> customer_master.customer_id','order_id -> transactions.order_id','transaction_id -> transactions.transaction_id','product_id -> product_master.product_id','agent_id -> agent_master.agent_id']}
RULES=['transaction_id is an order-line id, not a unit id; quantity is units.','order_id groups multiple transaction/order-line rows and can contain multiple products/sellers.','Historical transaction prices are snapshots; do not replace them with current product_master.current_price.','net_item_value is the line revenue after the modeled price/discount; gross_margin is stored at line level.','clickstream converting funnel is session_start -> home/search/category -> plp_view -> pdp_view -> add_to_cart -> checkout_start -> payment_attempt -> purchase -> session_end, with optional branches.','inventory closing_stock is never negative and is driven by units sold/received.','returns and reviews are downstream of delivered purchases.','Use observable warehouse tables for ML features; simulator latent profiles under data/_state are hidden evaluation truth.']
def main():
    cards=[]; md=['# Pantree Ecommerce Warehouse — Current Schema','',*['- '+x for x in RULES],'']
    for t in TABLES:
        p=D/f'{t}.parquet'
        if not p.exists(): continue
        df=pd.read_parquet(p); cols=[{'name':c,'dtype':str(df[c].dtype),'nullable':bool(df[c].isna().any())} for c in df.columns]
        card={'table':t,'grain':GRAIN[t],'primary_key':PK.get(t,''),'foreign_keys':FK.get(t,[]),'row_count':len(df),'columns':cols}; cards.append(card)
        md += [f'## `{t}`',f'**Grain:** {GRAIN[t]}',f'**Primary key:** `{PK.get(t,"")}`',f'**Rows:** {len(df):,}','','| column | dtype | nullable |','|---|---|---|']+[f"| `{c['name']}` | {c['dtype']} | {'yes' if c['nullable'] else 'no'} |" for c in cols]+['','**Foreign keys / joins:**']+[f'- {x}' for x in FK.get(t,[])]+['','---','']
    (OUT/'knowledge_base.md').write_text('\n'.join(md)); (OUT/'knowledge_base.json').write_text(json.dumps({'tables':cards,'business_rules':RULES},indent=2)); print('wrote current schema artifacts')
if __name__=='__main__': main()
